from .checkout_solution import checkout

def test_checkout_calculates_correct_total_prices():
    assert checkout("A") == 50
    assert checkout("B") == 30
    assert checkout("C") == 20
    assert checkout("D") == 15
    assert checkout("AA") == 100
    assert checkout("BB") == 45
    assert checkout("CC") == 40
    assert checkout("DD") == 30
    assert checkout("AAA") == 130
    assert checkout("BBB") == 75
    assert checkout("CCC") == 60
    assert checkout("DDD") == 45
    assert checkout("ABCD") == 115
    assert checkout("ABCDABCD") == 215
    assert checkout("AAABCCBBDAA") == 360
    assert checkout("a") == 50
    assert checkout("b") == 30
    assert checkout("c") == 20
    assert checkout("d") == 15
    assert checkout("aa") == 100
    assert checkout("bb") == 45
    assert checkout("cc") == 40
    assert checkout("dd") == 30
    assert checkout("aaa") == 130
    assert checkout("bbb") == 75
    assert checkout("ccc") == 60
    assert checkout("ddd") == 45
    assert checkout("abcd") == 115
    assert checkout("abcdabcd") == 215
    assert checkout("aaabccbbdaa") == 360
